# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Deploy Versioned Pages
description: Will push the documentation to the gh-pages branch, possibly with a versioned URL. When the PR is closed, the documentation will be deleted.
# Note: this has some shortcomings, like race conditions when multiple PRs are opened at the same time,
# problems with overwriting existing files, not deleting deleted files, etc.
# We'll address these when we transform this action into a truly reusable independent action.
# But for now, let's get it working!

inputs:
  source_folder:
    description: "Path to the html files to deploy in current working directory"
    required: false
  versions_file:
    description: "Path to the versions file on gh-pages branch"
    default: "versions.json"
  create_comment:
    description: "Create a comment on the PR with the URL to the documentation" # in case of PR
    default: "true"

outputs:
  target_folder:
    description: "The target folder for the documentation"
    value: ${{ steps.calc.outputs.target_folder }}

runs:
  using: "composite"
  steps:
    - name: Determine target_folder
      id: calc
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == 'pull_request_target' || "${{ github.event_name }}" == 'pull_request' ]]; then
          target_folder="pr-${{ github.event.pull_request.number }}"
        else
          target_folder="${{github.ref_name}}"
        fi
        echo "target_folder=$target_folder" >> $GITHUB_OUTPUT

    - name: Find Comment
      #if: ${{ github.event.pull_request != null }}
      uses: peter-evans/find-comment@v3
      continue-on-error: true
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        #comment-author: 'github-actions[bot]'
        body-includes: documentation
        
    - name: Output
      shell: bash
      run: |
        echo 'ndi'
        echo ${{ github.event.pull_request.number }}
        echo "next1:"
        echo ${{ steps.fc.outputs.comment-id }}
        echo "next2:"
        echo ${{ steps.fc.outputs.comment-node-id }}
        echo "next3:"
        echo ${{ steps.fc.outputs.comment-body }}
        echo "next4:"
        echo ${{ steps.fc.outputs.comment-author }}
        echo "next5:"
        echo ${{ steps.fc.outputs.comment-created-at }}

    - name: Comment on PR with docs URL
      if: ${{ github.event_name == 'pull_request_target' && inputs.create_comment == 'true' && steps.fc.outputs.comment-id == 0}}
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{github.event.pull_request.number}}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          The created documentation from the pull request is available at: [docu-html](https://eclipse-score.github.io/score/${{steps.calc.outputs.target_folder}})
        reactions: rocket
