# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation
on:
  pull_request_target:
    types: [opened, reopened, synchronize] # Handles forked PRs
  push:
  merge_group:
    types: [checks_requested]

jobs:
  docs-build:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the correct branch safely in all scenarios (PRs, forks, merges)
      # ------------------------------------------------------------------------------
      # | Condition                              | Event Type         | Checked Out Branch    |
      # |----------------------------------------|--------------------|-----------------------|
      # | github.head_ref                        | pull_request_target | PR branch (source branch) |
      # | github.event.pull_request.head.ref     | pull_request        | PR branch (source branch) |
      # | github.ref                             | push, merge_group   | The branch being pushed/merged |
      # ------------------------------------------------------------------------------
      # ------------------------------------------------------------------------------
      # Checkout the correct repository safely in all scenarios (PRs, forks, merges)
      # ------------------------------------------------------------------------------
      # | Condition                                      | Event Type         | Checked Out Repository           |
      # |------------------------------------------------|--------------------|----------------------------------|
      # | github.event.pull_request.head.repo.full_name  | pull_request       | Forked repository (if PR is from a fork) |
      # | github.repository                              | push, merge_group  | Default repository (same repo PRs, merges, pushes) |
      - name: Checkout repository (Handle all events)
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1

  docs-deploy:
    name: Deploy documentation to GitHub Pages
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: docs-build
    steps:

      - name: Deploy 🚀
        id: pages-deployment
        uses: ./.github/actions/deploy-versioned-pages
        with:
          source_folder: extracted_docs
