# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Cleanup Documentation
on:
  pull_request:
    types: [closed]
  delete:
jobs:
  docs-build-cleanup:
    name: Remove build documentation
    # Remove the corresponding documentation from the gh-pages branch,
    # after a PR is closed or a branch is deleted.
    runs-on: ubuntu-latest
    concurrency:
      group: gh-pages
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Remove version
        run: |
          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            VERSION="pr-${{ github.event.pull_request.number }}"
          else
            VERSION="${{ github.ref_name }}"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Delete the folder and remove the version from the versions file
          rm -rf "${VERSION}"

          # Remove from versions.json
          if [[ -f versions.json ]]; then
            jq --arg ver "$VERSION" 'map(select(.version != $ver))' versions.json > tmp.json && mv tmp.json versions.json
          fi
      - name: Push changes to gh-pages branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Cleanup ${{ env.VERSION }}"
          add: .
          new_branch: "gh-pages"
